components/Article.vue, pages/contents/articles/[slug].vue, pages/contents/partners.vue
Убрал спа переход у ссылок.
Добавил meta для хлебных крошек
=> change link type to articles

pages/contents/articles/[slug].vue
реальная ошибка 404 если статья не найдена
=> throw 404 if article not found

components/Select.vue
https://wirenboard.youtrack.cloud/issue/SOFT-4403
=> add space to dropdown items

pages/contents/integrators.vue
Переименовал в "Выберите регион"
https://wirenboard.youtrack.cloud/issue/SOFT-4404
=> change integrators select placeholder

content/ru/_articles/vizit_intercom.md
Обновлен url, теперь ссылка верна.
По задаче DOC-1743.
=> Update url vizit_intercom.md

content/ru/_articles/smart_restaurant.md
Обновлен url, теперь ссылка верна.
По задаче DOC-1743.
=> Update url smart_restaurant.md

content/ru/_articles/greenhouse_automating.md
Изменен заголовок. Заголовок дублировал другую статью и не соответствовал своей ссылке.
По задаче DOC-1743.
=> Update title greenhouse_automating.md

components/Map.vue, pages/contents/integrators.vue
Отфильтровываем интеграторов, которые не помещаются на карте
https://wirenboard.youtrack.cloud/issue/SOFT-4405
=> filter items on map changes

components/content/VideoPlayer.vue
исправил классический урл для картинок на _ipx версию
=> fix url with _ipx prefix

content/en/_integrators/abrom.md, content/en/_integrators/it_vision.md
=> Synthycat patch 7

content/en/_integrators/abrom.md, content/en/_integrators/it_vision.md, content/en/_integrators/tesliot.md
=> Synthycat patch 6

content/en/pages/legal-purchase-terms.md
[Задача Doc-1441](https://wirenboard.youtrack.cloud/issue/DOC-1441/Najti-i-vpisat-usloviya-pokupki-ot-kakogo-nibud-angloyazychnogo-sajta)
Требовалось обновить [имеющиеся Условия Покупки на английском](https://wirenboard.com/en/pages/legal-purchase-terms/):
- взять за основу [русские Условия Покупки](https://wirenboard.com/ru/pages/legal-purchase-terms/) (они уже работают для нас и покупателей),
- убрать из них всё специфичное для России, 
- привести к западному стандарту.
Проделанная работа:
Проследил, чтобы текст был юридически точно, лаконично и понятно сформулирован, а также соответствовал положениям, на которые мы уже опираемся. Взял за основу [русскую версию](https://wirenboard.com/ru/pages/legal-purchase-terms/), проверил соответствие юридических положений и обязательств в …
=> Create English legal-purchase-terms.md

components/content/Product.vue
=> fix product page

server/api/[locale]/catalog.ts
Добавил локализацию в апи каталога
=> add localization to catalog api

server/api/[locale]/catalog.ts
=> add different image sizes to catalog api

components/content/Gallery.vue
=> fix gallery relative paths

content/ru/pages/wbce2025.md
Не отобразились картинки, в рамках PR-213 для задачи [DOC-1969](https://wirenboard.youtrack.cloud/issue/DOC-1969/Zalit-v-zagolovok-novoe-foto-dlya-vystavki-WBCE2025) меняю описание wbce2025.md файла, убираю капс, чтобы всё отобразилось.
Проверил локально - работает.
=> edited wbce2025.md

components/content/ProductSolutions.vue, pages/contents/solutions/[slug].vue, pages/contents/solutions/index.vue
___________________________________
**Что происходит; кому и зачем нужно:**
Решили переименовать страницу "Примеры внедрений" в "Примеры использования"
___________________________________
**Что поменялось для пользователей:**
___________________________________
**Как проверял/а:**
___________________________________
**Чеклист ревью:**
=> edit ru title page solutions

content/en/catalog/wb-mge-v3.md
___________________________________
**Что происходит; кому и зачем нужно:**
У нас нет английского видео для товара, были русские вставлены. Убрал.
___________________________________
**Что поменялось для пользователей:**
Теперь они не будут смотреть видео на непонятном языке.
___________________________________
**Как проверял/а:**
Превью в редакторе.
___________________________________
**Чеклист ревью:**
=> Убрал русские видео с английской страницы.

components/content/Product.vue, pages/contents/product/[slug].vue
___________________________________
**Что происходит; кому и зачем нужно:**
один источник данных
___________________________________
**Что поменялось для пользователей:**
ничего
___________________________________
**Как проверял/а:**
локально
___________________________________
**Чеклист ревью:**
=> fix product data source
